global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Ton app NestJS (URL publique)
  - job_name: 'nestjs-olympia'
    scheme: https
    static_configs:
      - targets: ['kun-nestjs-develop.up.railway.app']
    metrics_path: '/internal/metrics'
